name = "lean-demo-20250502"
version = "0.1.0"
defaultTargets = ["False", "putnam_2005_a4"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.9.0"

[[lean_lib]]
name = "False"

[[lean_lib]]
name = "putnam_2005_a4"
